Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.host_name = "postgres"
  
    config.ssh.insert_key = false
    config.vm.provision "shell", inline: <<-SHELL
      echo "Updating system"
      sudo apt-get update
  
      echo "Installing postgres"
      sudo apt-get install -y postgresql postgresql-contrib
  
      systemctl start postgresql.service
  
      echo "Configuring and restarting PostgreSQL"
      echo 'listen_addresses = '"'"'*'"'" >> /etc/postgresql/14/main/postgresql.conf
      echo 'host    all             all             10.0.2.0/24            md5' >> /etc/postgresql/14/main/pg_hba.conf
      systemctl restart postgresql.service
  
      echo "Creating airat user and database"
  
      echo "CREATE USER airat"
      sudo -u postgres psql -c "CREATE USER airat WITH PASSWORD 'airat';"
  
      echo "CREATE ROLE admin WITH CREATEDB CREATEROLE"
      sudo -u postgres psql -c "CREATE ROLE admin WITH CREATEDB CREATEROLE;"
  
      echo "CREATE DATABASE testdb OWNER airat"
      sudo -u postgres psql -c "CREATE DATABASE testdb OWNER airat;"
  
      echo "Successfully created PostgreSQL dev virtual machine."
      echo ""
  
    SHELL
  
  end