---
- hosts: database
  become: yes
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: "Install packages"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - python3-psycopg2
        - postgresql-contrib   
        - acl  
  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql
          
    - name: Create a new database with name
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        comment: My test DB
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become_user: postgres

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "{{ db_path_pghba  }}"
        contype: host
        databases: all
        method: md5
        users: "{{ db_user }}"
        create: true
      become: yes
      become_user: postgres
      notify: restart postgres


    - name: "Load SQL script into a variable"
      set_fact:
        migration_sql: "{{ lookup('file', 'migration.sql') }}"

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
