---
- hosts: app
  become: true
  vars:
    container_count: 1
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      when: "'Ubuntu' in ansible_distribution"

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      when: "'Ubuntu' in ansible_distribution"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      when: "'Ubuntu' in ansible_distribution"


    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      when: "'Ubuntu' in ansible_distribution"

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
      when: 
        - "'CentOS' in ansible_distribution"

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
      when:
        - "'CentOS' in ansible_distribution" 

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
      when: 
        - "'CentOS' in ansible_distribution"

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes
      when:
        - "'CentOS' in ansible_distribution"

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes
      when: 
        - "'CentOS' in ansible_distribution"

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes
      when: 
        - "'CentOS' in ansible_distribution"

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
      when: 
        - "'CentOS' in ansible_distribution"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      when: 
        - "'CentOS' in ansible_distribution"


    - name: Install Docker Module for Python
      pip:
        name: docker    

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present

